
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: lisabuch_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: lisabuch_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: lisabuch_production
  pool: 5
  timeout: 5000

  env RAILS_ENV=production DATABASE_URL=postgresql://user:pass@127.0.0.1/immense-basin-69611_production bundle exec rake assets:precompile 2>&1